### ISSUE TITLE
DBus UID override

### ISSUE THREAD

**Issue by kiwiz** [Bluetooth-Devices/bluetooth-adapters#54]
**Is your feature request related to a problem? Please describe.**
I got around to testing https://github.com/home-assistant/core/pull/89925, which includes the `dbus-fast` changes to override the DBus UID: https://github.com/Bluetooth-Devices/dbus-fast/pull/188 https://github.com/Bluetooth-Devices/dbus-fast/pull/193. I tried adding support for this in `bleak` via https://github.com/hbldh/bleak/pull/1182. Unfortunately, I didn't realize that `bluetooth-adapters` also uses `dbus-fast`: https://github.com/Bluetooth-Devices/bluetooth-adapters/blob/793201485615c9739f2c0cd629060f363066c957/src/bluetooth_adapters/dbus.py#L94 (which results in bluetooth failing to initialize). For now, I've worked around this locally by just patching `dbus-fast`'s `auth.py`.

**Describe the solution you'd like**
Some mechanism for overriding the UID in `bluetooth-adapters`? I'm not sure what the best strategy is here. `BLEAK_DBUS_AUTH_UID` already exists. On one hand, it doesn't make sense for this library to depend on that env var. On the other, adding a new env var would require setting both.

**Additional context**

**Comment by bdraco** [comment]
If you propose a code change/PR for all libaries/apps involved I can probably give you some more constructive feedback.

**Comment by bdraco** [comment]
AFAICT this is complete. Let me know if thats not the case
